const imagePaths = [
  "./imgs/background waterfall white 1920x1200.jpg",
  "./imgs/background waterfall white 1920x1200-popup.jpg",
  "./imgs/Home-hero-photo1.jpg",
  "./imgs/Hraci-hero-photo (4).jpg",
  "./imgs/Timy-hero-photo.jpg",
  "./imgs/logos/Anaheim Ducks.jpg",
  "./imgs/logos/Arizona Coyotes.jpg",
  "./imgs/logos/Boston Bruins.jpg",
  "./imgs/logos/Buffalo Sabres.jpg",
  "./imgs/logos/Calgary Flames.jpg",
  "./imgs/logos/Carolina Hurricanes.jpg",
  "./imgs/logos/Colorado Avalanche.jpg",
  "./imgs/logos/Columbus Blue Jackets.jpg",
  "./imgs/logos/Dallas Stars.jpg",
  "./imgs/logos/Detroit Red Wings.jpg",
  "./imgs/logos/Edmonton Oilers.jpg",
  "./imgs/logos/Florida Panthers.jpg",
  "./imgs/logos/Chicago Blackhawks.jpg",
  "./imgs/logos/Los Angeles Kings.jpg",
  "./imgs/logos/Minnesota Wild.jpg",
  "./imgs/logos/Montréal Canadiens.jpg",
  "./imgs/logos/Nashville Predators.jpg",
  "./imgs/logos/New Jersey Devils.jpg",
  "./imgs/logos/New York Islanders.jpg",
  "./imgs/logos/New York Rangers.jpg",
  "./imgs/logos/Ottawa Senators.jpg",
  "./imgs/logos/Philadelphia Flyers.jpg",
  "./imgs/logos/Pittsburgh Penguins.jpg",
  "./imgs/logos/San Jose Sharks.jpg",
  "./imgs/logos/Seattle Kraken.jpg",
  "./imgs/logos/St. Louis Blues.jpg",
  "./imgs/logos/Tampa Bay Lightning.jpg",
  "./imgs/logos/Toronto Maple Leafs.jpg",
  "./imgs/logos/Vancouver Canucks.jpg",
  "./imgs/logos/Vegas Golden Knights.jpg",
  "./imgs/logos/Washington Capitals.jpg",
  "./imgs/logos/Winnipeg Jets.jpg",
];

export default imagePaths;
